### ISSUE TITLE
Suggestion embers addons 

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/wpc#10]
https://www.curseforge.com/minecraft/mc-mods/aetherworks 
Aetherworks is a mod that adds a 2nd teir of materials to embers and make the mod more interesting
https://www.curseforge.com/minecraft/mc-mods/soot
Soot is an embers mod that adds a few upgrades and cool new items to the mod including alchemy and alcohol

**Comment by Draconian4466** [comment]
I can make quests for these addons too if needed

**Comment by kreezxil** [comment]
yes please make quests for them

also one suggestion per issue

also both have been added
