### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by Azuraprincess** [kreezxil/wpc#12]
https://www.curseforge.com/minecraft/mc-mods/future-minecraft

This mod adds some features from 1.13 and 1.14 update without having the version bugs.

**Comment by Azuraprincess** [comment]
scratch the suggestion since mod author uses mcreator

**Comment by Draconian4466** [comment]
@Azuraprincess pretty sure you can close GitHub issues if you make them? not too sure

**Comment by kreezxil** [comment]
yes you can always close your own issues. try it on this one.
