### ISSUE TITLE
All the bugs i found

### ISSUE THREAD

**Issue by KobiiKobes** [kreezxil/wpc#16]
Gravestones keep spawning hordes of skeletons and never stop till the grave is destroyed or out of view

Morphing to a dragon forces the client to disconnect not crash just disconnect

Actually surprisingly thats all.

**Comment by Draconian4466** [comment]
@KobiiKobes One issue for each bug please so they can get solved and not just a long confusing stream of comments

**Comment by kreezxil** [comment]
deconfigured: skeleton spawns
blacklisted those dragons from the morphs
