### ISSUE TITLE
Mod suggestion 5 and final

### ISSUE THREAD

**Issue by KobiiKobes** [kreezxil/wpc#18]
Ender IO TiC

https://www.curseforge.com/minecraft/mc-mods/plustic

Most of the mods i suggested are just tinkers addons since it doesn't mesh with the other mods atm

**Comment by Draconian4466** [comment]
Isnt this just #17 ?

**Comment by KobiiKobes** [comment]
Sorry wrong link i tried this mod anyways and its broken so it doesn't matter
