### ISSUE TITLE
[suggestion]Blood magic

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/wpc#19]
Blood magic would work pretty well with this pack adds another magic mod for players to work with and has an addon to connect it to tinkers #20 cool items and things that can be used to help against dragons and can add diversity to the party for taking down dragons (Blood mage) I would also be willing to do quests for blood magic

**Comment by kreezxil** [comment]
if this is the mod that adds taint and that f'n liquid that eats the world
i'm not going to add it.

**Comment by Draconian4466** [comment]
Thats thaumcraft

**Comment by kreezxil** [comment]
abyssalcraft does this too

**Comment by kreezxil** [comment]
added
