### ISSUE TITLE
[suggestion]BloodMagic+Tinkers

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/wpc#20]
https://www.curseforge.com/minecraft/mc-mods/tinkering-with-blood-magic
This mod will connect blood magic to tinkers so you can have another cool armor trait and can help make armor however you want has a blood ring which increases the amount of baubles in the pack for more diversity

**Comment by kreezxil** [comment]
isn't this the mod that adds taint and that f'n liquid that eats the world?
ie bloodmagic

**Comment by kreezxil** [comment]
turns out I was thinking of abyssalcraft not thaumcraft as you suggested elsewhere.

also added
