### ISSUE TITLE
Mod Suggestion Oxygen 

### ISSUE THREAD

**Issue by xxkainexx** [kreezxil/wpc#21]
all of the oxygen mods 

Oxygen core
https://www.curseforge.com/minecraft/mc-mods/oxygen-core/files/2828277

Oxygen menu
https://www.curseforge.com/minecraft/mc-mods/oxygen-menu/files/2790252

Oxygen mail
https://www.curseforge.com/minecraft/mc-mods/oxygen-mail/files/2790259

Oxygen groups
https://www.curseforge.com/minecraft/mc-mods/oxygen-groups/files/2807054

Oxygen exchange
https://www.curseforge.com/minecraft/mc-mods/oxygen-exchange/files/2791647

Oxygen interaction
https://www.curseforge.com/minecraft/mc-mods/oxygen-interaction/files/2791650

Oxygen players list
https://www.curseforge.com/minecraft/mc-mods/oxygen-players-list/files/2804748

Oxygen friends list
https://www.curseforge.com/minecraft/mc-mods/oxygen-friends-list/files/2807053

Oxygen trade
https://www.curseforge.com/minecraft/mc-mods/oxygen-trade/files/2791643

Oxygen merchants
https://www.curseforge.com/minecraft/mc-mods/oxygen-merchants/files/2830407

Oxygen teleportation
https://www.curseforge.com/minecraft/mc-mods/oxygen-teleportation/files/2832489

I know i probably should put these in separate issue but they are from the same mod just the addons to them.

**Comment by kreezxil** [comment]
added
