### ISSUE TITLE
Modpack fixed some configs and such.

### ISSUE THREAD

**Issue by KobiiKobes** [kreezxil/wpc#24]
Couldn't export it right but i did it with the mods in the mod folder if you get what i mean.
Tried the mods the late game Dragon stuff is still some of the best gear you can get and nothing is really op or broken maybe smaller things only weeks of testing could bring up but nothing big as far as my eyes can tell.

Here is the google drive link. (Since its 200mb+ and i can only upload 10mb or less):
https://drive.google.com/open?id=1O_xuv9Xt7ASZh5ZJV0sDmXIWkviLc8FN

**Comment by Draconian4466** [comment]
@KobiiKobes cant put that in pastebin?

**Comment by KobiiKobes** [comment]
Not unless pastebin allows you to upload zips?

**Comment by KobiiKobes** [comment]
Also blood magic and its tinkers thing is in it i dont know what i does i just checked if it added any op mats

**Comment by KobiiKobes** [comment]
Properly Exported Pack ???????
[World.of.Dragons.-.Player.s.Choice-Build.E.zip](https://github.com/kreezxil/wpc/files/3940536/World.of.Dragons.-.Player.s.Choice-Build.E.zip)

Called it build E so it wouldn't overwrite my old pack

**Comment by kreezxil** [comment]
You're an admin now, and as such you can op yourself and help test the pack even more.
