### ISSUE TITLE
Prediction ... pack too fat

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/wpc#25]
after this preview is out I think you will easily feel the bloat and all of you will say it's slower than other packs.

you'll have to make some hard decisions on what to remove.

**Comment by KobiiKobes** [comment]
If anything has to go it would be decocraft biblocraft or that one that adds the 10000000s of facade blocks

**Comment by kreezxil** [comment]
I was hoping to have a pack that was as popular as it was 1.5 years ago in
the summer of 2018 and i think it did fit within an 8gb gaming system. But
this pack is right at the border of that. The gaming rig now has to be 12
to 16gb to run this pack. The bigger the pack the lower in popularity it
will have.

So yeah, all the decode stuff should go. But things like Little Titles,
Chisels, and Chisels and Bits they could stay. Ideally I would say no to
Chisels because of the shear amount of models it adds. Not an issue with
Chisels & Bits and Little Titles.

**Comment by KobiiKobes** [comment]
1 and a half years ago the standard for ram was 8gb now it is 16gb we have gone along way in 1 and a half years chisels and bits is not in the pack and it adds tons of bloat just chisels on its own is fine and we use it alot alot of these old and outdated mods that are replaced with newer and easier to run mods should go.

**Comment by KobiiKobes** [comment]
And this pack runs about 200 percent better than WOD19 and WODNA so i dont know what your worried about bloat for only kaine so far has had issues and thats because his pc is god awful crashes even without minecraft.

**Comment by kreezxil** [comment]
chisels and bits doesn't add bloat, you don't even know how that mod works

chisels does cause bloat

also little tiles wouldn't cause bloat either as it works on the same
concept as chisels and bits

And the standard for ram for computers is not the standard by which
minecraft players have computers that they expect modded to run with

**Comment by KobiiKobes** [comment]
If it was up to me i would delete about 10 mods that cause issues fix the configs add optifine or better fps and release the modpack it would run on about 5gb to 6gb but its your modpack your servers your everything. Chisels and bits is a filler mod imo not really that practical.

**Comment by KobiiKobes** [comment]
and by bloat i dont just mean fps or performance bloat
