### ISSUE TITLE
Mods to remove

### ISSUE THREAD

**Issue by KobiiKobes** [kreezxil/wpc#28]
We dont really need or use these mods and the just add lag.

BiblioCraft
Corail Pillar
Corail Pillar - Extension Quark & Botania
Decocraft
Landlust - Furniture
Opencomputers

**Comment by Draconian4466** [comment]
I would say remove landlust as we allready have alot of deco mods

**Comment by KobiiKobes** [comment]
Corail Pillar
Corail Pillar - Extension Quark & Botania

Already have items in other mods that are better or more easy to use

**Comment by kreezxil** [comment]
you realize that one you monkey heads actually requested open computers.

**Comment by kreezxil** [comment]
so just because you don't use it doesn't mean everyone else doesn't use it.

**Comment by KobiiKobes** [comment]
There are 4 of us that play consistently and not one of the other guys even knew they existed till yesterday

**Comment by Draconian4466** [comment]
Knew what existed?

**Comment by KobiiKobes** [comment]
Corail pillars in the pack

**Comment by Draconian4466** [comment]
Also do we have other mods that add pillars of different kinds and materials?

**Comment by KobiiKobes** [comment]
yes ender io adds some and botania each for their own mods and not of different materials

**Comment by KobiiKobes** [comment]
we dont have that many baubles anyways most if not all are botania

**Comment by kreezxil** [comment]
it's not *four of you that play.*

it's *four of you that are playtesting*.

*this pack is not live*. it's in* closed testing.* that's* why there are
very few of you.*

**Comment by KobiiKobes** [comment]
yes and we are the testers the ones who complain about problems and break things so you dont end up with alot of issues on day 1

**Comment by Draconian4466** [comment]
I think landlust should be removed because we have alot of other deco mods the other ones in this list i think should stay as i think they will be used

**Comment by Draconian4466** [comment]
Biblio craft should not be removed as it has been frequently used in all wod vers it has been in

**Comment by KobiiKobes** [comment]
okay bibliocraft seems fair and i agree on landlust

**Comment by kreezxil** [comment]
kobii you were supposed to be using JEI to blacklist recipes, i'm wondering if you did that?
