### ISSUE TITLE
Dimensional Doors mod

### ISSUE THREAD

**Issue by GraveCarver** [kreezxil/wpc#29]
https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors

would love this to be added :D

**Comment by kreezxil** [comment]
what's a little more fat

**Comment by kreezxil** [comment]
and yes make your quest lines for it

I'm updating WODNA next today, and then this evening, i'm going to update WPC, and release it to the wild. now that we are making quest lines in it.

**Comment by kreezxil** [comment]
added
