### ISSUE TITLE
[Remove]better questing 

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/wpc#30]
Unless there is a use for it i dont really see a reason to keep this mod

**Comment by kreezxil** [comment]
what drugs are you on?

it's not in the current pack

![image](https://user-images.githubusercontent.com/3880072/70727645-9b6d7b80-1cc5-11ea-8f12-bce71272e83f.png)

**Comment by Draconian4466** [comment]
Oh i just looked at #5 for the mod list
