### ISSUE TITLE
[issue]Where are the mobs?

### ISSUE THREAD

**Issue by Draconian4466** [kreezxil/wpc#34]
i got on wpc today and noticed there are very few animals and I didn't see any mobs other than the skelliton horses which when you get close are struck by lightning and spawn skelliton riders.

**Comment by kreezxil** [comment]
maybe you guys killed them all or someone did a butcher command, lots of
admin in there.

**Comment by Draconian4466** [comment]
Possibly but why are there no hostiles at night?
