### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by KobiiKobes** [kreezxil/wpc#9]
CleanView
Clumps
Appleskin
AmbientSounds 3
Neat
SwingThroughGrass

Most if not all are client sided or quality of life mods that are missing or could do with being added.

**Comment by Draconian4466** [comment]
Cosmetic armor reworked

**Comment by kreezxil** [comment]
next time @KobiiKobes @Draconian4466 one mod suggestion per issue.

**Comment by kreezxil** [comment]
add have been added
